### ISSUE TITLE
[Feature Request] Possibility to modify the %ASYD% variable

### ISSUE THREAD

**Issue by JustDevNull** [AsydSolutions/ASYD#114]
By default the monit configuration allows the IP of the variable %ASYD% but in my case this was a problem, because I'm running the ASYD server in a VM at my local network and that made ASYD unable to monitor the status of the machine because obviously it was allowing the local IP and not the public one.

To fix that I had to modify the "data/deploys/monit/configs/monitrc" like this:

set httpd port 2812 and
    allow XXX.XXX.XXX.XXX
    allow 127.0.0.1
    allow asyd:<%MONIT_PW%>

It would be great if that variable can be modified through "System Settings" or making two variables %ASYD_LOCAL% and %ASYD_EXTERNAL%, were the last one was the autodetected external IP.

**Comment by JustDevZero** [comment]
I like better the second one, **%ASYD_EXTERNAL%** and **%ASYD_LOCAL%** just for one thing:
Imagine that you have servers in the _LAN_ that are not accesible from the _outside_ somehow, for example the typical internal database servers.

Having the external only could drive us into a reverse paradigm, allowing us to check every machine in the _internet_ but none at _intranet_.

**Comment by Choms** [comment]
If you look at the code:

    asyd = host.get_asyd_ip
    ...

    def get_asyd_ip
      ip = UDPSocket.open {|s| s.connect(self.ip, 1); s.addr.last}
      return ip
    end

It should actually open a connection to the host and pick the address used on the connection (which should be always the same interface it uses for connecting to that host, thus not giving issues). If this is not working we should check on it, as making two variables shouldn't be necessary.

**Comment by JustDevZero** [comment]
@Choms Yeah it opens a connection to the host and picks the address used on a **UDP** conection, which should be always the same interface but the IP that you normally access.

The problem that @JustDevNull got is that his ASYD instance is behind a router with **TCP** forwarding.

What happens here it's a bit confusing but easy to understand...
![diagrama1](https://cloud.githubusercontent.com/assets/172759/13588188/2c8d0b1e-e4ce-11e5-9a86-b0194ea7879c.png)

**Comment by Choms** [comment]
Ok, gotcha, proposed fix:

    def get_asyd_ip
      cmd = "echo $SSH_CLIENT | awk '{ print $1}'"
      ip = self.exec_cmd(cmd).strip
      return ip
    end

That should return the IP actually connecting to the SSH session which, in your graphic, would be the external one. I've tested this on debian, fedora and freebsd and seems to work, I'm a bit busy atm but will check it on solaris and openbsd later.
