### ISSUE TITLE
Distinguish between servers with "issues" and servers "offline" at the counting numbers in groups

### ISSUE THREAD

**Issue by JustDevNull** [AsydSolutions/ASYD#119]
I would be nice to have the possibility to see at the counting numbers of the groups which ones are "okay", which have "issues" and which are "offline", this way it will be better because it's more serious a "offline" state than RAM & CPU load and will be easier to see at a glance.

Of course at that point will be better to have it monitored with Zabbix, Nagios or other monitoring systems, but sometimes I have host added in ASYD days before they will added to Zabbix (my case) through a deploy.

**Comment by Choms** [comment]
Done, it'll be included on tomorrow's release (v1.1.0)

I'm closing this!
