### ISSUE TITLE
[faq] "-bash: warning: setlocale: LC_ALL: cannot change locale" on SSH connections breaks host adding

### ISSUE THREAD

**Issue by Fusl** [AsydSolutions/ASYD#44]
When adding a host which displays "-bash: warning: setlocale: LC_ALL: cannot change locale" when ssh-ing to it (no locales package installed), the frontend throws a stacktrace. Once installing the necessary packages and configuring locales correctly with the below commands, adding a host works without problems.

```
apt-get update
apt-get -y install locales
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
echo "#  File generated by update-locale" > /etc/default/locale
locale-gen
update-locale
```

**Comment by Choms** [comment]
Closing, merged into "troubleshooting" #81
