### ISSUE TITLE
Cron/Schedule deploys

### ISSUE THREAD

**Issue by Fusl** [AsydSolutions/ASYD#51]
Can we get a cron/schedule function where people can set cron-like syntax for deploys? (e.g. add a button next to the "Deploy!" button which says "Schedule" and give the user the choice to schedule a deploy one-time (execute once at *date*) or recurring (cron-like style "0 */12 * * *" or similar)).

**Comment by Fusl** [comment]
Hi! Does the closing of this feature request mean 'no'?

**Comment by Choms** [comment]
nah, I have it noted, I'm just cleaning up old issues, I'll tell you if there's any updates regarding this, but for now take it as a "maybe"
