### ISSUE TITLE
[faq] Nested if/endif breaks deploy

### ISSUE THREAD

**Issue by Fusl** [AsydSolutions/ASYD#71]
A deploy built somehow like that
```
if <%PKG_MANAGER%> == apt
    if <%VAR:something%> == somethingelse
        var somethingelse = exec: echo test
    endif
endif
```
breaks the entire deploy (ASYD says ```Bad formatting, check your deploy file```).
If you remove the inner if/endif this deploy runs fine.
PS: It does not matter if the variable in the second if does or does not exist, you can change it to %PKG_MANAGER% and it still would break the deploy.

**Comment by Choms** [comment]
For now ASYD doesn't supports nested conditional blocks, it will be studied and included on future releases, but that requires restructuring the deploy function

**Comment by Choms** [comment]
This is solved on devel, will push to master soon

**Comment by Choms** [comment]
Pushed to master, I'm closing this
