### ISSUE TITLE
[faq] RH firewall-cmd w/ ASYD monitoring

### ISSUE THREAD

**Issue by JustDevZero** [AsydSolutions/ASYD#88]
Like I already said multiple times RH distros, such as centos normally have firewall by default, but we can detect it in the nowadays:
firewall-cmd --state
returns "running" if it's running.

firewall-cmd --get-default-zone
prints the default zone (normally the active one)

We should use --get-active-zones, but we will need to parse it's content... :/
Link to manpages:
http://linuxmanpages.net/manpages/fedora20/man1/firewall-cmd.1.html

firewall-cmd --permanent --zone=CURRENT-ZONE --add-rich-rule="rule family="ipv4" source address="IP.OF.ASYD.SERVER/MASK.ADDRESS" port protocol="tcp" port="2812" accept
puts ASYD address trafic comming from Monit port

firewall-cmd  --reload
Needed to reload the firewalld rules and apply the new ones, also it answers with "success" if everything was ok

Somehow we need to do it in monit deploy, otherwise must be done by hand

**Comment by Choms** [comment]
I'll implement it native, in the meantime, there's a deploy who fixes this:

# Enable Monit port with firewall-cmd
#
var fw_zone = exec: firewall-cmd --get-default-zone 
exec: firewall-cmd --permanent --zone=<%VAR:fw_zone%> --add-rich-rule='rule family="ipv4" source address="<%ASYD%>/24" port protocol="tcp" port="2812" accept'
exec: firewall-cmd --reload

**Comment by Choms** [comment]
Now this operation is performed by the monit deploy itself, check the referenced commit. Will close as soon as we merge all this into master.
