### ISSUE TITLE
Status alert not triggering changes

### ISSUE THREAD

**Issue by JustDevNull** [AsydSolutions/ASYD#91]
I created a monitor called "disk" with the following rules:

check filesystem rootfs with path /
if space usage > 80% then alert

Then filled the server with data to exceed that amount but the Status alert still shows "all ok" but the server tab shows the following:

services: 	rootfs: space usage 89.8% matches resource limit [space usage>80.0%] 

![cap1](https://cloud.githubusercontent.com/assets/12670733/8061140/b5015940-0ec9-11e5-8765-07979774e076.PNG)
![cap2](https://cloud.githubusercontent.com/assets/12670733/8061141/b50298a0-0ec9-11e5-8244-60c460e81b59.PNG)
![cap3](https://cloud.githubusercontent.com/assets/12670733/8061142/b5048480-0ec9-11e5-81ba-83f6e0d966ed.PNG)

Can you check it please?

Thanks!

**Comment by Choms** [comment]
Hi!

What version of ASYD are you using? Also, it stills happens after restarting ASYD?
It looks like the monitoring daemon (which updates the server status and triggers the notifications) crashed, I will take a deeper look but that info would help me.

Cheers!

**Comment by JustDevNull** [comment]
The version is 0.08.

After restarting ASYD the error shows correctly.

Just in case I deleted the junk to see if the status changed to ok and it went well, and refilling the HDD showed the error correctly.

All is good now, sorry for the inconvenience.
