### ISSUE TITLE
Add support for Fedora 22 (and newer RH distros)

### ISSUE THREAD

**Issue by JustDevZero** [AsydSolutions/ASYD#92]
We need support for Fedora 22, and soon in Centos.

In the nowadays yum is deprecated and must be used "dnf" instead.

It have the same syntax, so it could be pretty easy.

If I'm able I will try by my self and make a PR.

**Comment by Fusl** [comment]
Hi,

can you check if https://github.com/Fusl/ASYD/tree/dev-02 works as expected for you with dnf?

**Comment by JustDevZero** [comment]
Haven't tested yes (away from pc these days) but looks good

**Comment by Fusl** [comment]
Mind testing and reporting back if it works? Would like to only push this into ASYD/master if it's really working as expected.

Thanks!

**Comment by Choms** [comment]
Implemented and working on #96, thank you guys ;)

Closing!
