### ISSUE TITLE
Missing 'sudo' shows wrong error message

### ISSUE THREAD

**Issue by Fusl** [AsydSolutions/ASYD#97]
Hi,

if the command ```sudo``` is missing on a newly added host, ASYD throws the error message

```Unable to monitor host fvz-rec-lv-rix-01: Host fvz-rec-lv-rix-01 doesn't support the 'service' command (line 40)```

Which is wrong. I haven't looked over the code but it's very likely that ASYD checks if the command exists by running ```sudo service --help``` or something, but it fails because ```sudo``` doesn't exist.

We should first try and check if ```sudo``` exists before continuing here, shouldn't we?

**Comment by Choms** [comment]
Actually, the existence of sudo is checked when adding the host (and only if the user is not root), not when deploying (and if the user isn't root and there's no sudo you cannot add the host). Please check the value of package_mgr on the variables list inside the host detail.

**Comment by Fusl** [comment]
Well, apparently something is wrong then because when I add a new host with user ```root``` it runs every command with ```sudo``` prepended.
